#pragma once

#ifndef GAG_ENABLE_BLE_MOUSE
// #define GAG_ENABLE_BLE_MOUSE GAG_HAVE_BLE_MOUSE
#define GAG_ENABLE_BLE_MOUSE 1
#endif
#define MASTER_HAND 1

#ifndef GAG_ENABLE_VIBRATION
#define GAG_ENABLE_VIBRATION 1
#endif

#ifndef GAG_AUTO_CAPTURE_SW_NEUTRAL
#define GAG_AUTO_CAPTURE_SW_NEUTRAL 1
#endif

#ifndef GAG_AUTO_CAPTURE_MINOR_ROTATION_FIX
#define GAG_AUTO_CAPTURE_MINOR_ROTATION_FIX 1
#endif

#ifndef GAG_APPLY_MINOR_ROTATION_OFFSET
#define GAG_APPLY_MINOR_ROTATION_OFFSET 1
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_AT_BOOT
#define GAG_MEASURE_HW_OFFSETS_AT_BOOT 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_THUMB
#define GAG_MEASURE_HW_OFFSETS_SENSOR_THUMB 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_INDEX
#define GAG_MEASURE_HW_OFFSETS_SENSOR_INDEX 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_MIDDLE
#define GAG_MEASURE_HW_OFFSETS_SENSOR_MIDDLE 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_RING
#define GAG_MEASURE_HW_OFFSETS_SENSOR_RING 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_LITTLE
#define GAG_MEASURE_HW_OFFSETS_SENSOR_LITTLE 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_GY25
#define GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_GY25 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_MPU9250
#define GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_MPU9250 0
#endif

#ifndef GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_GY511
#define GAG_MEASURE_HW_OFFSETS_SENSOR_WRIST_GY511 0
#endif

#ifndef GAG_HW_CALIBRATION_REQUIRED_SAMPLES
#define GAG_HW_CALIBRATION_REQUIRED_SAMPLES 500
#endif

#ifndef GAG_HW_CALIBRATION_SAMPLE_DELAY_MS
#define GAG_HW_CALIBRATION_SAMPLE_DELAY_MS 100
#endif

#ifndef GAG_HW_CALIBRATION_APPLY_UNSTABLE
#define GAG_HW_CALIBRATION_APPLY_UNSTABLE 1
#endif

#ifndef GAG_TFT_ROTATION
#define GAG_TFT_ROTATION 0
#endif

#ifndef GAG_ENABLE_FIFO_REPORT
#define GAG_ENABLE_FIFO_REPORT 0
#endif

#ifndef GAG_ENABLE_WRIST_MPU_PROBE_LOG
#define GAG_ENABLE_WRIST_MPU_PROBE_LOG 0
#endif

#ifndef GAG_ENABLE_SERIAL_SENSOR_QUAT_LOG
#define GAG_ENABLE_SERIAL_SENSOR_QUAT_LOG 0
#endif

#ifndef GAG_ENABLE_RECOGNITION
#define GAG_ENABLE_RECOGNITION 1
#endif

#ifndef GAG_VIZ_HAND_RELATIVE_ROTATION
#define GAG_VIZ_HAND_RELATIVE_ROTATION 1
#endif

#ifndef GAG_VIZ_CUBES_RELATIVE_ROTATION
#define GAG_VIZ_CUBES_RELATIVE_ROTATION 0
#endif

#ifndef GAG_APPLY_GY511_WRIST_PIVOT_ROTATION_FIX
#define GAG_APPLY_GY511_WRIST_PIVOT_ROTATION_FIX 1
#endif

#ifndef GAG_SERIAL_SENSOR_QUAT_LOG_INTERVAL_MS
#define GAG_SERIAL_SENSOR_QUAT_LOG_INTERVAL_MS 100
#endif

#ifndef GAG_PRINT_MINOR_ROTATION_OFFSET_CANDIDATES
#define GAG_PRINT_MINOR_ROTATION_OFFSET_CANDIDATES 1
#endif

#ifndef GAG_MINOR_ROTATION_OFFSET_PRINT_INTERVAL_MS
#define GAG_MINOR_ROTATION_OFFSET_PRINT_INTERVAL_MS 5000UL
#endif

#ifndef GAG_TTGO_RIGHT_BUTTON_PIN
#define GAG_TTGO_RIGHT_BUTTON_PIN 0
#endif

#ifndef GAG_TTGO_BUTTON_ACTIVE_LOW
#define GAG_TTGO_BUTTON_ACTIVE_LOW 1
#endif

#ifndef GAG_TTGO_BUTTON_DEBOUNCE_MS
#define GAG_TTGO_BUTTON_DEBOUNCE_MS 250UL
#endif

#ifndef GAG_PAIR_CONFIRM_BUTTON_PIN
#define GAG_PAIR_CONFIRM_BUTTON_PIN 35
#endif

#ifndef GAG_PAIR_CONFIRM_BUTTON_ACTIVE_LOW
#define GAG_PAIR_CONFIRM_BUTTON_ACTIVE_LOW 1
#endif

#ifndef GAG_PAIR_CONFIRM_TIMEOUT_MS
#define GAG_PAIR_CONFIRM_TIMEOUT_MS 10000UL
#endif

#define GAG_ENABLE_PERIODIC_SOFT_SENSOR_RESET 1
// #ifndef GAG_PERIODIC_SOFT_SENSOR_RESET
  #ifdef GAG_ENABLE_PERIODIC_SOFT_SENSOR_RESET
    // #define GAG_PERIODIC_SOFT_SENSOR_RESET GAG_ENABLE_PERIODIC_SOFT_SENSOR_RESET
    #define GAG_PERIODIC_SOFT_SENSOR_RESET 1
  #else
    #define GAG_PERIODIC_SOFT_SENSOR_RESET 0
  #endif
// #endif

#ifndef GAG_PERIODIC_SOFT_SENSOR_RESET_INTERVAL_MS
// #define GAG_PERIODIC_SOFT_SENSOR_RESET_INTERVAL_MS 300000UL
#define GAG_PERIODIC_SOFT_SENSOR_RESET_INTERVAL_MS 15000UL
#endif

#ifndef GAG_USE_MPU_DMP_QUAT_FIFO
#define GAG_USE_MPU_DMP_QUAT_FIFO 0
#endif

#ifndef GAG_ENABLE_MPU_FIFO
#define GAG_ENABLE_MPU_FIFO 1
#endif

#ifndef GAG_ENABLE_MPU9250_FIFO
#define GAG_ENABLE_MPU9250_FIFO 1
#endif

#ifndef GAG_FIFO_RESET_INTERVAL_MS
#define GAG_FIFO_RESET_INTERVAL_MS 50
#endif

#ifndef GAG_MPU_FIFO_DLPF_CFG
#define GAG_MPU_FIFO_DLPF_CFG 0x04u
#endif

#ifndef GAG_MPU_FIFO_SMPLRT_DIV
#define GAG_MPU_FIFO_SMPLRT_DIV 9u
#endif

#ifndef GAG_ENABLE_FIFO_BOOT_TEST
#define GAG_ENABLE_FIFO_BOOT_TEST 1
#endif

#ifndef GAG_MPU6050_FIFO_MAX_BYTES
#define GAG_MPU6050_FIFO_MAX_BYTES 1024U
#endif

#ifndef GAG_MPU9250_FIFO_MAX_BYTES
#define GAG_MPU9250_FIFO_MAX_BYTES 512U
#endif

#define GAG_PRIMARY_WRIST_SENSOR_GY25 0
#define GAG_PRIMARY_WRIST_SENSOR_MPU9250 1
#define GAG_PRIMARY_WRIST_SENSOR_GY511 2

#ifndef GAG_PRIMARY_WRIST_SENSOR
#define GAG_PRIMARY_WRIST_SENSOR GAG_PRIMARY_WRIST_SENSOR_GY25
#endif
